In [1]:

# Dependencies
import requests
import json
import pandas as pd
import numpy as np
from pprint import pprint
api_format = "json"
from sqlalchemy import create_engine

Part 1- getting data

In [2]:
# for loop for different API 
li=[]
name_q=['games','teams','tips']

for q in name_q:
    s="https://api.squiggle.com.au/?q="+q+";format=json"
    li.append(s)

In [3]:
#p print to check the json data
#pprint(requests.get(li[0]).json())

In [4]:
#convering json data into dataframe 
df_games=pd.DataFrame.from_dict(pd.json_normalize(requests.get(li[0]).json()['games']),orient='columns')

In [5]:
#clean data-Remove columns that we dont needed, rename columns names to make it  clear\n
df_clean=df_games.drop(columns=['localtime', 'date','tz','is_grand_final','complete','is_final','id',
                                'hteamid','ateamid','winnerteamid','updated','round'])
#rename column and assign it into "Games"
Games=df_clean.rename(columns={'abehinds': 'away_behinds', 'hteam': 'home_team','hgoals': 'home_goals','hscore': 'home_score','hgoals': 'home_goals','ascore': 'away_score','agoals': 'away_goals','ateam': 'away_team','hbehinds': 'home_behinds'}) 
Games.head()

,home_behinds,year,away_score,away_behinds,home_score,home_team,home_goals,venue,away_team,away_goals,roundname,winner
0,5.0,2017,132,12.0,89,Carlton,14.0,M.C.G.,Richmond,20.0,Round 1,Richmond
1,14.0,2017,100,10.0,86,Collingwood,12.0,M.C.G.,Western Bulldogs,15.0,Round 1,Western Bulldogs
2,10.0,2017,110,8.0,82,Sydney,12.0,S.C.G.,Port Adelaide,17.0,Round 1,Port Adelaide
3,12.0,2017,120,12.0,90,St Kilda,13.0,Docklands,Melbourne,18.0,Round 1,Melbourne
4,12.0,2017,98,8.0,96,Gold Coast,14.0,Carrara,Brisbane Lions,15.0,Round 1,Brisbane Lions

In [6]:
#adding new columns to calculate points and assign state to each team 
Games['points_away']=Games.away_goals+Games.away_behinds
Games['points_home']=Games.home_goals+Games.home_behinds

Games.head()

,home_behinds,year,away_score,away_behinds,home_score,home_team,home_goals,venue,away_team,away_goals,roundname,winner,points_away,points_home
0,5.0,2017,132,12.0,89,Carlton,14.0,M.C.G.,Richmond,20.0,Round 1,Richmond,32.0,19.0
1,14.0,2017,100,10.0,86,Collingwood,12.0,M.C.G.,Western Bulldogs,15.0,Round 1,Western Bulldogs,25.0,26.0
2,10.0,2017,110,8.0,82,Sydney,12.0,S.C.G.,Port Adelaide,17.0,Round 1,Port Adelaide,25.0,22.0
3,12.0,2017,120,12.0,90,St Kilda,13.0,Docklands,Melbourne,18.0,Round 1,Melbourne,30.0,25.0
4,12.0,2017,98,8.0,96,Gold Coast,14.0,Carrara,Brisbane Lions,15.0,Round 1,Brisbane Lions,23.0,26.0

In [7]:
#  if condition to assign states to each team 
Games.loc[(Games['home_team'] == 'Richmond') | (Games['home_team'] == 'Western Bulldogs') | (Games['home_team'] == 'Melbourne')
          | (Games['home_team'] == 'Hawthorn')| (Games['home_team'] == 'Geelong')| (Games['home_team'] == 'Collingwood')
          | (Games['home_team'] == 'Essendon')| (Games['home_team'] == 'St Kilda')| (Games['home_team'] == 'North Melbourne')
          | (Games['home_team'] == 'Carlton'),'state']='Victoria' 
Games.loc[(Games['home_team'] == 'Greater Western Sydney') | (Games['home_team'] == 'Sydney') ,'state']='New South Wales'
Games.loc[(Games['home_team'] == 'Brisbane Lions') | (Games['home_team'] == 'Gold Coast') ,'state']='Queensland'
Games.loc[(Games['home_team'] == 'Port Adelaide') | (Games['home_team'] == 'Adelaide') ,'state']='South Australia'
Games.loc[(Games['home_team'] == 'West Coast') | (Games['home_team'] == 'Fremantle') ,'state']='Western Australia'
#df_clean2.loc[(df_clean2['first_name'] != 'Bill') & (df['first_name'] != 'Emma'), 'name_match'] = 'Mismatch'  
Games.head()

,home_behinds,year,away_score,away_behinds,home_score,home_team,home_goals,venue,away_team,away_goals,roundname,winner,points_away,points_home,state
0,5.0,2017,132,12.0,89,Carlton,14.0,M.C.G.,Richmond,20.0,Round 1,Richmond,32.0,19.0,Victoria
1,14.0,2017,100,10.0,86,Collingwood,12.0,M.C.G.,Western Bulldogs,15.0,Round 1,Western Bulldogs,25.0,26.0,Victoria
2,10.0,2017,110,8.0,82,Sydney,12.0,S.C.G.,Port Adelaide,17.0,Round 1,Port Adelaide,25.0,22.0,New South Wales
3,12.0,2017,120,12.0,90,St Kilda,13.0,Docklands,Melbourne,18.0,Round 1,Melbourne,30.0,25.0,Victoria
4,12.0,2017,98,8.0,96,Gold Coast,14.0,Carrara,Brisbane Lions,15.0,Round 1,Brisbane Lions,23.0,26.0,Queensland

In [8]:
#calculate the average points by state 

Points=Games.groupby(['state']).agg({'points_away':'sum','points_home':'sum','year':'count'}).reset_index()
Points['total points']=Points.points_away+Points.points_home

#every game has been count twice
Points['average_points']=round(Points['total points']/Points['year']*2,1)
Points.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   state           5 non-null      object
 1   points_away     5 non-null      float64
 2   points_home     5 non-null      float64
 3   year            5 non-null      int64
 4   total points    5 non-null      float64
 5   average_points  5 non-null      float64
dtypes: float64(4), int64(1), object(1)
memory usage: 368.0+ bytes

In [9]:
#getting a list of venue names to get coordinate later 
Games['venue'].unique()

array(['M.C.G.', 'S.C.G.', 'Docklands', 'Carrara', 'Adelaide Oval',
       'Subiaco', 'Sydney Showground', 'Gabba', 'Bellerive Oval',
       'UNSW Canberra Oval', 'University of Tasmania Stadium',
       'Adelaide Arena at Jiangwan Stadium', 'GMHBA Stadium',
       'Traeger Park', 'Marrara Oval', "Cazaly's Stadium", 'Mars Stadium',
       'Optus Stadium', 'Manuka Oval', 'Kardinia Park', 'York Park',
       'Stadium Australia', 'Football Park', 'Blacktown', 'Wellington',
       'Perth Stadium', 'Marvel Stadium', 'Eureka Stadium',
       'Jiangwan Stadium', 'Riverway Stadium'], dtype=object)

In [10]:
#loading players data from csv  
Players=pd.read_csv('stats.csv', encoding='utf-8') 
#Players.info()
#Players.head()

In [11]:
# getting certain columns for data we need for visualization 
Players=Players[['team','year','displayName','Disposals','Kicks','Marks','Handballs','Goals','Behinds','Hit Outs','Tackles']]
Players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89470 entries, 0 to 89469
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   team         89470 non-null  object
 1   year         89470 non-null  int64
 2   displayName  89470 non-null  object
 3   Disposals    89470 non-null  int64
 4   Kicks        89470 non-null  int64
 5   Marks        89470 non-null  int64
 6   Handballs    89470 non-null  int64
 7   Goals        89470 non-null  int64
 8   Behinds      89470 non-null  int64
 9   Hit Outs     89470 non-null  int64
 10  Tackles      89470 non-null  int64
dtypes: int64(9), object(2)
memory usage: 7.5+ MB

Part II: Connecting to SQL

In [12]:
# connecting 
connection_string = "postgres:password@localhost:5432/Project_2"
engine = create_engine(f'postgresql://{connection_string}')

In [13]:
# transform data
Games.to_sql(name='Games', con=engine, if_exists='replace', index=False)
Players.to_sql(name='Players', con=engine, if_exists='replace', index=False)
Points.to_sql(name='Points', con=engine, if_exists='replace', index=False)

In [14]:
# checking table has been created successfully
engine.table_names()

<ipython-input-14-d99326451cb6>:2: SADeprecationWarning: The Engine.table_names() method is deprecated and will be removed in a future release.  Please refer to Inspector.get_table_names(). (deprecated since: 1.4)
  engine.table_names()

['Games', 'Players', 'Points']

In [15]:
# checking data has been loaded successfully
pd.read_sql_query('select * from "Games"', con=engine).head()

,home_behinds,year,away_score,away_behinds,home_score,home_team,home_goals,venue,away_team,away_goals,roundname,winner,points_away,points_home,state
0,5.0,2017,132,12.0,89,Carlton,14.0,M.C.G.,Richmond,20.0,Round 1,Richmond,32.0,19.0,Victoria
1,14.0,2017,100,10.0,86,Collingwood,12.0,M.C.G.,Western Bulldogs,15.0,Round 1,Western Bulldogs,25.0,26.0,Victoria
2,10.0,2017,110,8.0,82,Sydney,12.0,S.C.G.,Port Adelaide,17.0,Round 1,Port Adelaide,25.0,22.0,New South Wales
3,12.0,2017,120,12.0,90,St Kilda,13.0,Docklands,Melbourne,18.0,Round 1,Melbourne,30.0,25.0,Victoria
4,12.0,2017,98,8.0,96,Gold Coast,14.0,Carrara,Brisbane Lions,15.0,Round 1,Brisbane Lions,23.0,26.0,Queensland

In [16]:
Games.to_csv (r'Games.csv', index = False, header=True)

In [17]:
Players.to_csv (r'Players.csv', index = False, header=True)